# Generated by Django 4.1.4 on 2022-12-11 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventario', models.IntegerField()),
                ('velocidad', models.FloatField()),
                ('nombre', models.CharField(max_length=120)),
                ('desc', models.CharField(max_length=3200)),
                ('peso_maximo', models.FloatField()),
                ('icono', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_inicio', models.FloatField()),
                ('lon_inicio', models.FloatField()),
                ('hora_inicio', models.DateTimeField()),
                ('lat_fin', models.FloatField()),
                ('lon_fin', models.FloatField()),
                ('hora_fin', models.DateTimeField()),
                ('dron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dron')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
