# Generated by Django 4.1.4 on 2022-12-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dron_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='dron',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
